### ISSUE TITLE
Is it possible to change the terminal font used?

### ISSUE THREAD

**Issue by AcinonXDev** [JaySandhu/neovim-mac#14]
The default font is one that does not properly render certain special characters like symbols. I would like to change the font to MesloLGS NF, my preferred terminal font. I don't see an option for this in the settings, and the solutions I've found online involving ginit.vim are specific to nvim-qt and fvim, which are obviously not the same program as this one.

**Comment by JaySandhu** [comment]
You can change the font with Neovim's [guifont](https://neovim.io/doc/user/options.html#'guifont') option. To set it to MesloLGS NF, you can run this command:

```
set guifont=MesloLGS NF
```

You can add that line to your `init.vim` to set the font at startup. You can also set the point size by appending it to the end of the font name like so:

```
set guifont=MesloLGS NF:h16
```

Also, ensure that the font is installed on your system.

**Comment by AcinonXDev** [comment]
I tried this, but the font doesn't seem to change. Symbols are still showing as question marks. Here's the difference between my terminal (using MesloLGS NF as the font) and the GUI when running the command to set the font:
<img width="697" alt="Screenshot 2022-12-16 at 3 39 47 PM" src="https://user-images.githubusercontent.com/88356560/208185261-0092160a-b3eb-498c-a7ab-019221b8df08.png">
<img width="1104" alt="Screenshot 2022-12-16 at 3 40 52 PM" src="https://user-images.githubusercontent.com/88356560/208185413-6fdeaa68-ae1c-4a87-910e-cd474da3a908.png">

**Comment by JaySandhu** [comment]
Oh I see. Could be a rendering bug, I will install that font and investigate.

**Comment by JaySandhu** [comment]
Managed to get it working. A couple things:

1. Neovim doesn't load `ginit.vim`, even for GUIs. So we need to set `guifont` in `init.vim`, this shouldn't cause you any issues because the setting is ignored for terminals.
2. We need to append "Regular" to the end of the font name (to use the regular font, as opposed to the bold, or italic variations). Bold and italic syntax groups will still render correctly.
3. I forgot to escape spaces in the `set guifont` commands above, whoops. The correct syntax:

```
set guifont=MesloLGS\ NF\ Regular
```

Or if you prefer:

```
let &guifont="MesloLGS NF Regular"
```

Either will work, just paste one into your `init.vim` file.
 
<img width="1039" alt="Screen Shot 2022-12-17 at 1 43 21 PM" src="https://user-images.githubusercontent.com/10956772/208245271-9b30696f-9f88-405f-9c8f-efbc07609fc1.png">

**Comment by AcinonXDev** [comment]
Okay, I'll see if it works. Thanks!
