### ISSUE TITLE
build script fails on Catalina

### ISSUE THREAD

**Issue by johnzim** [JaySandhu/neovim-mac#2]
Hiya - looking forward to trying out this GUI 🙂 I thought I'd submit an issue with the build shell script.

If you don't already have `cmake` or any other other tools like `automake` or `autoconf` installed the neovim installer will fail on building Neovim, but unfortunately the build script just checks if the `Neovim` folder is there, (which it still will be if there's a failed build) so that step gets skipped and the build fails.

**Comment by JaySandhu** [comment]
Right, I see the problem. I think I'll adapt the script to check for `neovim/bin` instead (which should only exist after the first successful build / install). The build script should probably do `set -e` at the start because at the moment it's doing no error checking.

Thanks for the reporting the issue.
